version: '3'
services:
  nginx:
    image: nginx:latest
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    ports:
      - "888:80"
    depends_on:
      - flask
      - react
  react:
    build:
      context: ./gpt-api-usage-tracker
    depends_on:
      - flask
    ports:
      - "3000:3000"
  flask:
    container_name: flask
    build: 
      context: ./flask
      dockerfile: Dockerfile
    ports:
     - "5000:5000"
    
  #reverse proxy -> loadbalancer 
  #docker-compose down
  # docker-compose up --force-recreate --scale flask=5
  # docker-compose build --no-cache

